In [3]:
# -*- coding: UTF-8 -*-
import pandas as pd
import xlrd
import re

file = '编码20150228最终版(查).xlsx'
df = pd.read_excel(file)
spec = df['规格型号']

In [106]:
blank = df[spec.str.isspace()]
blank

Empty DataFrame
Columns: [属性名, Unnamed: 1, 是核心业务属性, 出现次数, 规格型号]
Index: []

In [163]:
space = df[spec.str.contains(' ')]
space

       属性名 Unnamed: 1  是核心业务属性  出现次数         规格型号
1   DPA抽样数      重要数据项     True     6      1221 12
11  不合格样品数      重要数据项     True     2  2007space

In [186]:
rightSpace = df[spec.str.match(r'.*\s$')]
r = rightSpace['规格型号'].str.extract(r'([\S]+)')
r

            0
11  2007space

In [72]:
lowerCaseRows = df[spec.str.islower()]
lowerCaseRows

     属性名 Unnamed: 1  是核心业务属性  出现次数   规格型号
16  二筛费用      重要数据项     True     5  qweer

In [139]:
df[spec.str.match(r'.*[a-z].*')]

        属性名 Unnamed: 1  是核心业务属性  出现次数    规格型号
5   DPA试验结论      重要数据项     True     1  2000kW
14   二筛收费大类      重要数据项     True     1   1N21n
16     二筛费用      重要数据项     True     5   qweer

In [154]:
df[spec.str.match(r'[^0-9a-zA-Z]*$')]

     属性名 Unnamed: 1  是核心业务属性  出现次数     规格型号
2  DPA状态      重要数据项     True     3  １２２１－１２

In [141]:
df[spec.str.match(r'.*[0]{3}[W]')]

     属性名 Unnamed: 1  是核心业务属性  出现次数   规格型号
4  DPA试验      重要数据项     True     1  2000W

In [148]:
lower = df[spec.str.match(r'.*[a-z].*')]
lower[~lower['规格型号'].str.contains('kW')]

       属性名 Unnamed: 1  是核心业务属性  出现次数   规格型号
14  二筛收费大类      重要数据项     True     1  1N21n
16    二筛费用      重要数据项     True     5  qweer

In [9]:
my_string = "2000"
re.search(r'([0-9]*)', my_string) != None

True

In [2]:
df[spec.str.match(r'(.*[_].*)|(.*[－].*)')]

NameError: name 'df' is not defined

In [ ]:
df.to_excel('excel_output.xls')